program ::= statement
          | statement ";" program

statement ::= assignment
            | expression

assignment ::= identifier "=" expression

expression ::= term
             | expression "+" term
             | expression "-" term

term ::= factor
       | term "*" factor

factor ::= number
         | identifier
         | "(" expression ")"

identifier ::= letter
             | identifier letter

number ::= digit
         | number digit

letter ::= "a" | "b" | ... | "z" | "A" | "B" | ... | "Z"

digit ::= "0" | "1" | ... | "9"
